### ISSUE TITLE
Smartthings button connection drops

### ISSUE THREAD

**Issue by kebel87** [dmulcahey/zha-device-handlers#271]
Hi, 

first time I'm reporting a bug and I'm fairly new to Home assistant. I recently bought smartthings button and they works for a couple of minutes, then drops for no reason.

Here is all the info I could gather. Is it enough to spot/understand what's wrong? 

Thanks

----

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | America/Toronto
version | 0.105.4
virtualenv | false

I'm using **Nortek Zigbee/zwave stick (husbzb-1)**

Silicon Labs EZSP
EZSP
by Silicon Labs
IEEE:
00:0d:6f:00:11:f5:e1:93
Nwk:
0x0000
Device Type:
Coordinator
LQI:
255
RSSI:
Unknown
Last Seen:
2020-02-16T12:07:04
Power Source:
Mains
Quirk:
bellows.zigbee.application.EZSPCoordinator

-----

Here's the ZHA info for smartthings button 

Samjin button
button
by Samjin
IEEE:
28:6d:97:00:01:0d:9f:0b
Nwk:
0xbc46
Device Type:
EndDevice
LQI:
255
RSSI:
-70
Last Seen:
2020-02-16T11:52:04
Power Source:
Battery or Unknown
Quirk:
zhaquirks.samjin.button.SamjinButton

----

Here's the log of when I paired it : 

[0x0000:zdo] ZDO request 0x0036: [60, <Bool.false: 0>]
Device 0x4bfb (28:6d:97:00:01:0d:9f:0b) joined the network
[0x4bfb] Requesting 'Node Descriptor'
[0x4bfb] Extending timeout for 0x1a request
Device 0x8f8a (28:6d:97:00:01:0d:9f:0b) joined the network
Device 28:6d:97:00:01:0d:9f:0b changed id (0x4bfb => 0x8f8a)
Canceling old initialize call
[0x8f8a] Requesting Node Descriptor failed: 
[0x8f8a] Discovering endpoints
[0x8f8a] Extending timeout for 0x1c request
[0x8f8a] Requesting 'Node Descriptor'
[0x8f8a] Extending timeout for 0x1e request
Device 0x8f8a (28:6d:97:00:01:0d:9f:0b) joined the network
Skip initialization for existing device 28:6d:97:00:01:0d:9f:0b
[0x8f8a:zdo] ZDO request 0x0013: [0x8f8a, 28:6d:97:00:01:0d:9f:0b, 128]
[0x8f8a] Discovered endpoints: [1]
[0x8f8a:1] Discovering endpoint information
[0x8f8a] Extending timeout for 0x20 request
[0x8f8a] Node Descriptor: <Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4673 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=11264 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>
[0x8f8a] Discovering endpoints
[0x8f8a] Extending timeout for 0x22 request
[0x8f8a:1] Discovered endpoint information: <SimpleDescriptor endpoint=1 profile=260 device_type=1026 device_version=0 input_clusters=[0, 1, 3, 32, 1026, 1280, 2821] output_clusters=[3, 25]>
[0x8f8a] Extending timeout for 0x24 request
[0x8f8a] Discovered endpoints: [1]
[0x8f8a:1] Discovering endpoint information
[0x8f8a] Extending timeout for 0x26 request
Ignoring message (b'182401040000420653616d6a696e0500004206627574746f6e') on cluster 0: unknown endpoint or cluster id: 'No cluster ID 0x0000 on (28:6d:97:00:01:0d:9f:0b, 1)'
[0x8f8a:1] Discovered endpoint information: <SimpleDescriptor endpoint=1 profile=260 device_type=1026 device_version=0 input_clusters=[0, 1, 3, 32, 1026, 1280, 2821] output_clusters=[3, 25]>
[0x8f8a] Extending timeout for 0x28 request
[0x8f8a:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=40 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1] Manufacturer: Samjin
[0x8f8a:1] Model: button
Checking quirks for Samjin button (28:6d:97:00:01:0d:9f:0b)
Considering <class 'zhaquirks.samjin.button.SamjinButton'>
Found custom device replacement for 28:6d:97:00:01:0d:9f:0b: <class 'zhaquirks.samjin.button.SamjinButton'>
device - 0x8f8a:28:6d:97:00:01:0d:9f:0b entering async_device_initialized - is_new_join: True
device - 0x8f8a:28:6d:97:00:01:0d:9f:0b has joined the ZHA zigbee network
[0x8f8a](button): started configuration
[0x8f8a:ZDO](button): channel: 'async_configure' stage succeeded
[0x8f8a] Extending timeout for 0x2a request
[0x8f8a] Extending timeout for 0x2c request
[0x8f8a] Extending timeout for 0x2e request
[0x8f8a:1:0x0000]: bound 'basic' cluster: Status.SUCCESS
[0x8f8a:1:0x0000]: finished channel configuration
[0x8f8a] Extending timeout for 0x30 request
[0x8f8a:1:0x0001]: bound 'power' cluster: Status.SUCCESS
[0x8f8a] Extending timeout for 0x32 request
[0x8f8a:1:0x0402]: bound 'temperature' cluster: Status.SUCCESS
[0x8f8a] Extending timeout for 0x34 request
[0x8f8a:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=48 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0000]: initializing channel: from_cache: False
[0x8f8a:1:0x0000]: channel: 'async_configure' stage succeeded
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=50 command_id=Command.Configure_Reporting_rsp>
[0x8f8a:1:0x0402] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=52 command_id=Command.Configure_Reporting_rsp>
[0x8f8a:1:0x0500]: started IASZoneChannel configuration
[0x8f8a] Extending timeout for 0x36 request
[0x8f8a:1:0x0001]: reporting 'battery_voltage' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
[0x8f8a:1:0x0402]: reporting 'measured_value' attr on 'temperature' cluster: 30/900/50: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
[0x8f8a:1:0x0500]: bound 'ias_zone' cluster: Status.SUCCESS
[0x8f8a] Extending timeout for 0x38 request
[0x8f8a] Extending timeout for 0x3a request
[0x8f8a:1:0x0402]: finished channel configuration
[0x8f8a:1:0x0402]: channel: 'async_configure' stage succeeded
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=56 command_id=Command.Write_Attributes_rsp>
[0x8f8a:1:0x0500]: wrote cie_addr: 00:0d:6f:00:11:f5:e1:93 to 'ias_zone' cluster: [<WriteAttributesStatusRecord status=Status.SUCCESS>]
[0x8f8a:1:0x0500]: finished IASZoneChannel configuration
[0x8f8a] Extending timeout for 0x3c request
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=58 command_id=Command.Configure_Reporting_rsp>
[0x8f8a:1:0x0001]: reporting 'battery_percentage_remaining' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=60 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0500]: channel: 'async_configure' stage succeeded
[0x8f8a:1:0x0001]: finished channel configuration
[0x8f8a:1:0x0001]: channel: 'async_configure' stage succeeded
[0x8f8a](button): completed configuration
[0x8f8a](button): stored in registry: ZhaDeviceEntry(name='Samjin button', ieee='28:6d:97:00:01:0d:9f:0b', last_seen=1581858254.960896)
[0x8f8a](button): started initialization
[0x8f8a:ZDO](button): entry loaded from storage: ZhaDeviceEntry(name='Samjin button', ieee='28:6d:97:00:01:0d:9f:0b', last_seen=1581858254.960896)
[0x8f8a:ZDO](button): channel: 'async_initialize' stage succeeded
[0x8f8a] Extending timeout for 0x3e request
[0x8f8a] Extending timeout for 0x40 request
[0x8f8a] Extending timeout for 0x42 request
[0x8f8a:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=62 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0000]: initializing channel: from_cache: False
[0x8f8a:1:0x0000]: channel: 'async_initialize' stage succeeded
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=64 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0402] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=66 command_id=Command.Read_Attributes_rsp>
Device 0x1566 (00:15:8d:00:02:27:27:29) left the network
[0x8f8a] Extending timeout for 0x44 request
[0x8f8a] Extending timeout for 0x46 request
[0x8f8a:1:0x0402]: initializing channel: from_cache: False
[0x8f8a:1:0x0402]: channel: 'async_initialize' stage succeeded
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=68 command_id=Command.Read_Attributes_rsp>
[0x8f8a] Extending timeout for 0x48 request
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=70 command_id=Command.Read_Attributes_rsp>
[0x8f8a] Extending timeout for 0x4a request
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=72 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0500]: initializing channel: from_cache: False
[0x8f8a:1:0x0500]: channel: 'async_initialize' stage succeeded
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=74 command_id=Command.Read_Attributes_rsp>
[0x8f8a] Extending timeout for 0x4c request
[0x8f8a:1:0x0001] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=76 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0001]: initializing channel: from_cache: False
[0x8f8a:1:0x0001]: channel: 'async_initialize' stage succeeded
[0x8f8a](button): power source: Battery or Unknown
[0x8f8a](button): completed initialization
[0x8f8a:zdo] ZDO request 0x0036: [180, <Bool.true: 1>]
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=21 command_id=1>
[0x8f8a:1:0x0500] ZCL request 0x0001: [IasZoneType(name='manufacturer_specific_0x8000', value=32768), 4673]
[0x8f8a:1:0x0500]: Enroll requested
[0x8f8a] Extending timeout for 0x4e request
[0x8f8a] Extending timeout for 0x50 request
[0x8f8a:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=80 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0000] ZCL request 0x0001: [[<ReadAttributeRecord attrid=4 status=Status.SUCCESS value=Samjin>]]
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=22 command_id=0>
[0x8f8a:1:0x0500] ZCL request 0x0000: [1, 0, 0, 0]
[0x8f8a:1:0x0500]: Updated alarm state: 1
Device 0xc6f9 (00:15:8d:00:01:6c:42:c6) left the network
[0x8f8a:1:0x0500] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=23 command_id=0>
[0x8f8a:1:0x0500] ZCL request 0x0000: [1, 0, 0, 0]
[0x8f8a:1:0x0500]: Updated alarm state: 1
[0x8f8a] Extending timeout for 0x52 request
[0x8f8a:1:0x0000] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=82 command_id=Command.Read_Attributes_rsp>
[0x8f8a:1:0x0000] ZCL request 0x0001: [[<ReadAttributeRecord attrid=5 status=Status.SUCCESS value=button>]]

----

Here is some log entry copied from HA log 

[0xbc46:1:0x0500]: channel: 'async_configure' stage failed ex:
11:52 AM components/zha/core/channels/__init__.py (WARNING) - message first occurred at 11:30 AM and shows up 2 times

----

Sun Feb 16 2020 08:39:09 GMT-0500 (heure normale de l’Est nord-américain)
Failed ZDO request during device initialization: [0x8a1d:0:0x0005]: Message send failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 89, in _initialize
    epr = await self.zdo.Active_EP_req(self.nwk, tries=3, delay=2)
  File "/usr/local/lib/python3.7/site-packages/zigpy/util.py", line 88, in retry
    r = await func()
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 187, in request
    self.nwk, dst_ep, cluster
zigpy.exceptions.DeliveryError: [0x8a1d:0:0x0005]: Message send failure

**Comment by Adminiuga** [comment]
according to the log, the Samjin Button with `ieee = 28:6d:97:00:01:0d:9f:0b` and `NWK = 0x8f8a`, joined and initialized normally.

There was some other device `Device 0x1566 (00:15:8d:00:02:27:27:29) left the network` deciding to leave the network and these messages
```
[0xbc46:1:0x0500]: channel: 'async_configure' stage failed ex:
11:52 AM components/zha/core/channels/init.py (WARNING) - message first occurred at 11:30 AM 
and shows up 2 times
...
Failed ZDO request during device initialization: [0x8a1d:0:0x0005]: Message send failure
```

Are from unrelated devices.

**Comment by kebel87** [comment]
0xbc46 is indeed the SmartThings button as of 11h52 this morning. 0x8f8a was earlier this morning when I first paired it. I’ve deleted and paired it again, which explains the network name change.

However I’m clueless as to why it drops from network. :/

**Comment by dmulcahey** [comment]
this isn't a quirks issue. if you are still experiencing an issue I would suggest seeking help in the zigbee channel on discord or on the forums.
